markdown:         kramdown
highlighter:         rouge
paginate:         4

title:            风之缘的博客
url:              https://wulijun.github.io/
feed:             /atom.xml
author:
    name:         风之缘
    email:        wulijun01234@gmail.com
description:      "风之缘的博客，区块链,数字货币,AI,Golang,PHP等相关技术的研究和新闻分享，以及记录对互联网行业的思考和分析。"
keywords: "blockchain,bitcoin,AI,eos,ipfs,sia,Lightning Network,Digital Currency,Cryptocurrency,PHP,PHP扩展,PHP内核,PHP内核分析,PHP Runtime,PHP Extension,风之缘,wulijun,wulijun01234"
about: 			  "互联网老兵,关注区块链,AI,Golang,PHP等技术的发展与应用"
follow:
    github:       https://github.com/wulijun


style: 			 /css/style.css
blogName: 		  风之缘
blogDesc: 		 "区块链,数字货币,AI,Golang,PHP等相关技术的研究和新闻分享，以及记录对互联网行业的思考和分析。"
